#!/usr/bin/python
#-- coding:utf-8

import sys

default_encoding = 'utf-8'
if sys.getdefaultencoding() != default_encoding:
    reload(sys)
    sys.setdefaultencoding(default_encoding)


lua_config_table = {
    #table名字        way:0表示常规转换方式，1表示特殊转换方式, 2表示地图转换
	#"attackdefine" : { "way":1},
    #"activity" : { "way":0},
    #"map_1234" : { "way":2},
	"creature_layout" : { "way":0},
	"creature_template" : { "way":0},
	"map_template" : { "way":0},
	"player_template" : { "way":0},
	"item_template" : { "way":0},
	"npc_chatter_text" : { "way":0},
	"effect_config" : { "way":0},
	"recipe" : { "way":0},
	"Tabgroup" : { "way":0},
	"action" : { "way":0},
	"actiontodo" : { "way":0},
	"misc" : { "way":0},
    "lootdropper" : {"way":0},
    "monster_template" : {"way":0},
    "resource_template" : {"way":0},
    "structure_template" : {"way":0},
    "item_template_new" : {"way":0},
    "weapon" : {"way":0},
    "eater" : {"way":0},
    "equippable" : {"way":0},
    "growable" : {"way":0},
    "armor" : {"way":0},
    "tool" : {"way":0},
    "text" : {"way":0},
    "pickable" : {"way":0},
    "growable" : {"way":0},
    "action_player" : {"way":0},
    "creature_template_new" : {"way":0},
    "attribute" : {"way":0},
    "burnable" : {"way":0},
    "workable" : {"way":0},
    "fuel" : {"way":0},
    "cookable" : {"way":0},
    "structure_tech" : {"way":0},
    "edible" : {"way":0},
    "creature_target" : {"way":0},
    "buff" : {"way":0},
    "sleeper" : {"way":0},
    "sanityaura" : {"way":0},
	"light" : {"way":0},
	"spawner" : {"way":0},
	"action_player_timeline" : {"way":0},
	"regrowth" : {"way":0},
	"crop" : {"way":0},
	"grower" : {"way":0},
	"container" : {"way":0},
	"cookbook" : {"way":0},
	"foodingredients" : {"way":0},
	"physics" : {"way":0},
	"gamesetting" : {"way":0},
	"Freshness" : {"way":0},
	"map_1000" : { "way":2},
	"map_1001" : { "way":2},
	"trapable" : { "way":0},
	"trap" : { "way":0},
	"dryable" : { "way":0},
	"growmath" : { "way":0},
	"layup" : { "way":0},
	"walls" : { "way":0},
    "fertilizer" : { "way":0},
    "creature_level" : { "way":0},
    "level" : { "way":0},
    "item_level" : { "way":0},
    "live_level" : { "way":0},
	"trader" : { "way":0},
	"skill" : { "way":0},
	"ser_effect" : { "way":0},
	"groundspeed" : { "way":0},
	"taskbuildarea" : { "way":0},
	"recommendname" : { "way":0},
}


