local  groundspeed_lua_config = {
[ 2 ]={  id = 2, name = [==[ROAD]==], speed = 1.3,},
[ 3 ]={  id = 3, name = [==[ROCKY]==], speed = 0.5,},
[ 4 ]={  id = 4, name = [==[DIRT]==], speed = 1.0,},
[ 5 ]={  id = 5, name = [==[SAVANNA]==], speed = 1.0,},
[ 6 ]={  id = 6, name = [==[GRASS]==], speed = 1.0,},
[ 7 ]={  id = 7, name = [==[FOREST]==], speed = 1.0,},
[ 8 ]={  id = 8, name = [==[MARSH]==], speed = 1.0,},
[ 9 ]={  id = 9, name = [==[WEB]==], speed = 0.6,},
[ 10 ]={  id = 10, name = [==[WOODFLOOR]==], speed = 1.0,},
[ 11 ]={  id = 11, name = [==[CARPET]==], speed = 1.0,},
[ 12 ]={  id = 12, name = [==[CHECKER]==], speed = 1.0,},
[ 13 ]={  id = 13, name = [==[CAVE]==], speed = 1.0,},
[ 14 ]={  id = 14, name = [==[FUNGUS]==], speed = 1.0,},
[ 15 ]={  id = 15, name = [==[SINKHOLE]==], speed = 0.5,},
[ 16 ]={  id = 16, name = [==[UNDERROCK]==], speed = 1.0,},
[ 17 ]={  id = 17, name = [==[MUD]==], speed = 1.0,},
[ 18 ]={  id = 18, name = [==[BRIK]==], speed = 1.0,},
[ 19 ]={  id = 19, name = [==[BRICK_GLOW]==], speed = 1.0,},
[ 20 ]={  id = 20, name = [==[TILES]==], speed = 1.0,},
[ 21 ]={  id = 21, name = [==[TILES_GLOW]==], speed = 1.0,},
[ 22 ]={  id = 22, name = [==[TRIM]==], speed = 1.0,},
[ 23 ]={  id = 23, name = [==[TRIM_GLOW]==], speed = 1.0,},
[ 24 ]={  id = 24, name = [==[FUNGUSRED]==], speed = 1.0,},
[ 25 ]={  id = 25, name = [==[FUNGUSGREEN]==], speed = 1.0,},
[ 30 ]={  id = 30, name = [==[DECIDUOUS]==], speed = 1.0,},
[ 31 ]={  id = 31, name = [==[DESERT_DIRT]==], speed = 1.0,},
[ 32 ]={  id = 32, name = [==[SCALE]==], speed = 1.0,},
[ 33 ]={  id = 33, name = [==[LAVAARENA_FLOOR]==], speed = 1.0,},
[ 34 ]={  id = 34, name = [==[LAVAARENA_TRIM]==], speed = 1.0,},
[ 35 ]={  id = 35, name = [==[QUAGMIRE_PEATFOREST]==], speed = 1.0,},
[ 36 ]={  id = 36, name = [==[QUAGMIRE_PARKFIELD]==], speed = 1.0,},
[ 37 ]={  id = 37, name = [==[QUAGMIRE_PARKSTONE]==], speed = 1.0,},
[ 38 ]={  id = 38, name = [==[QUAGMIRE_GATEWAY]==], speed = 1.0,},
[ 39 ]={  id = 39, name = [==[QUAGMIRE_SOIL]==], speed = 1.0,},
[ 41 ]={  id = 41, name = [==[QUAGMIRE_CITYSTONE]==], speed = 1.0,},
}

return  groundspeed_lua_config