local  live_level_lua_config = {
[ 2000 ]={  index = 2000, stagenum = 0, stateid = 0, name = [==[Sapling]==], resourcebaseproficiency = 2, toolproficiency = 0,},
[ 2001 ]={  index = 2001, stagenum = 0, stateid = 0, name = [==[Grass]==], resourcebaseproficiency = 2, toolproficiency = 0,},
[ 2002 ]={  index = 2002, stagenum = 0, stateid = 0, name = [==[Berrybush]==], resourcebaseproficiency = 2, toolproficiency = 0,},
[ 2003 ]={  index = 2003, stagenum = 1, stateid = 0, name = [==[sapling _Evergreen]==], resourcebaseproficiency = 2, toolproficiency = 0,},
[ 2004 ]={  index = 2004, stagenum = 2, stateid = 0, name = [==[Short Evergreen]==], resourcebaseproficiency = 2, toolproficiency = 0,},
[ 2005 ]={  index = 2005, stagenum = 3, stateid = 0, name = [==[Normal Evergreen]==], resourcebaseproficiency = 2, toolproficiency = 0,},
[ 2006 ]={  index = 2006, stagenum = 4, stateid = 0, name = [==[Tall Evergreen]==], resourcebaseproficiency = 2, toolproficiency = 0,},
[ 2007 ]={  index = 2007, stagenum = 5, stateid = 0, name = [==[Old Evergreen]==], resourcebaseproficiency = 2, toolproficiency = 0,},
[ 2008 ]={  index = 2008, stagenum = 0, stateid = 3, name = [==[Evergreen stump]==], resourcebaseproficiency = 2, toolproficiency = 0,},
[ 2009 ]={  index = 2009, stagenum = 0, stateid = 0, name = [==[Carrot]==], resourcebaseproficiency = 2, toolproficiency = 0,},
[ 2010 ]={  index = 2010, stagenum = 0, stateid = 0, name = [==[Boulder]==], resourcebaseproficiency = 2, toolproficiency = 0,},
[ 2011 ]={  index = 2011, stagenum = 0, stateid = 0, name = [==[Gold Vein]==], resourcebaseproficiency = 2, toolproficiency = 0,},
[ 2012 ]={  index = 2012, stagenum = 2, stateid = 1, name = [==[Short Evergreen]==], resourcebaseproficiency = 2, toolproficiency = 0,},
[ 2013 ]={  index = 2013, stagenum = 3, stateid = 1, name = [==[Normal Evergreen]==], resourcebaseproficiency = 2, toolproficiency = 0,},
[ 2014 ]={  index = 2014, stagenum = 4, stateid = 1, name = [==[Tall Evergreen]==], resourcebaseproficiency = 2, toolproficiency = 0,},
[ 2015 ]={  index = 2015, stagenum = 5, stateid = 1, name = [==[Old Evergreen]==], resourcebaseproficiency = 2, toolproficiency = 0,},
[ 2016 ]={  index = 2016, stagenum = 0, stateid = 2, name = [==[Sapling]==], resourcebaseproficiency = 2, toolproficiency = 0,},
[ 2017 ]={  index = 2017, stagenum = 0, stateid = 2, name = [==[Grass]==], resourcebaseproficiency = 2, toolproficiency = 0,},
[ 2018 ]={  index = 2018, stagenum = 0, stateid = 2, name = [==[Berrybush]==], resourcebaseproficiency = 2, toolproficiency = 0,},
[ 2019 ]={  index = 2019, stagenum = 0, stateid = 0, name = [==[Flower]==], resourcebaseproficiency = 2, toolproficiency = 0,},
[ 2020 ]={  index = 2020, stagenum = 0, stateid = 0, name = [==[Rose]==], resourcebaseproficiency = 2, toolproficiency = 0,},
[ 2021 ]={  index = 2021, stagenum = 1, stateid = 0, name = [==[spiderden]==], resourcebaseproficiency = 2, toolproficiency = 0,},
[ 2022 ]={  index = 2022, stagenum = 2, stateid = 0, name = [==[spiderden]==], resourcebaseproficiency = 2, toolproficiency = 0,},
[ 2023 ]={  index = 2023, stagenum = 3, stateid = 0, name = [==[spiderden]==], resourcebaseproficiency = 2, toolproficiency = 0,},
[ 2121 ]={  index = 2121, stagenum = 0, stateid = 0, name = [==[corn plant]==], resourcebaseproficiency = 2, toolproficiency = 0,},
[ 2122 ]={  index = 2122, stagenum = 0, stateid = 0, name = [==[carrot plant]==], resourcebaseproficiency = 2, toolproficiency = 0,},
[ 2123 ]={  index = 2123, stagenum = 0, stateid = 0, name = [==[watermelon plant]==], resourcebaseproficiency = 2, toolproficiency = 0,},
[ 2124 ]={  index = 2124, stagenum = 0, stateid = 0, name = [==[sweet_potato plant]==], resourcebaseproficiency = 2, toolproficiency = 0,},
[ 2125 ]={  index = 2125, stagenum = 0, stateid = 0, name = [==[dragonfruit plant]==], resourcebaseproficiency = 2, toolproficiency = 0,},
[ 2126 ]={  index = 2126, stagenum = 0, stateid = 0, name = [==[durian plant]==], resourcebaseproficiency = 2, toolproficiency = 0,},
[ 2127 ]={  index = 2127, stagenum = 0, stateid = 0, name = [==[pomegranate plant]==], resourcebaseproficiency = 2, toolproficiency = 0,},
[ 2128 ]={  index = 2128, stagenum = 0, stateid = 0, name = [==[eggplant plant]==], resourcebaseproficiency = 2, toolproficiency = 0,},
[ 2129 ]={  index = 2129, stagenum = 7, stateid = 0, name = [==[pumpkin plant]==], resourcebaseproficiency = 2, toolproficiency = 0,},
[ 2130 ]={  index = 2130, stagenum = 0, stateid = 6, name = [==[corn plant]==], resourcebaseproficiency = 2, toolproficiency = 0,},
[ 2131 ]={  index = 2131, stagenum = 0, stateid = 6, name = [==[carrot plant]==], resourcebaseproficiency = 2, toolproficiency = 0,},
[ 2132 ]={  index = 2132, stagenum = 0, stateid = 6, name = [==[watermelon plant]==], resourcebaseproficiency = 2, toolproficiency = 0,},
[ 2133 ]={  index = 2133, stagenum = 0, stateid = 6, name = [==[sweet_potato plant]==], resourcebaseproficiency = 2, toolproficiency = 0,},
[ 2134 ]={  index = 2134, stagenum = 0, stateid = 6, name = [==[dragonfruit plant]==], resourcebaseproficiency = 2, toolproficiency = 0,},
[ 2135 ]={  index = 2135, stagenum = 0, stateid = 6, name = [==[durian plant]==], resourcebaseproficiency = 2, toolproficiency = 0,},
[ 2136 ]={  index = 2136, stagenum = 0, stateid = 6, name = [==[pomegranate plant]==], resourcebaseproficiency = 2, toolproficiency = 0,},
[ 2137 ]={  index = 2137, stagenum = 0, stateid = 6, name = [==[eggplant plant]==], resourcebaseproficiency = 2, toolproficiency = 0,},
[ 2138 ]={  index = 2138, stagenum = 1, stateid = 6, name = [==[pumpkin plant]==], resourcebaseproficiency = 2, toolproficiency = 0,},
[ 2073 ]={  index = 2073, stagenum = 0, stateid = 0, name = [==[Red_Mushroom]==], resourcebaseproficiency = 2, toolproficiency = 0,},
[ 2074 ]={  index = 2074, stagenum = 0, stateid = 0, name = [==[Green_mushroom]==], resourcebaseproficiency = 2, toolproficiency = 0,},
[ 2075 ]={  index = 2075, stagenum = 0, stateid = 0, name = [==[Blue_mushroom]==], resourcebaseproficiency = 2, toolproficiency = 0,},
[ 2139 ]={  index = 2139, stagenum = 0, stateid = 7, name = [==[Red_Mushroom]==], resourcebaseproficiency = 2, toolproficiency = 0,},
[ 2140 ]={  index = 2140, stagenum = 0, stateid = 7, name = [==[Green_mushroom]==], resourcebaseproficiency = 2, toolproficiency = 0,},
[ 2141 ]={  index = 2141, stagenum = 0, stateid = 7, name = [==[Blue_mushroom]==], resourcebaseproficiency = 2, toolproficiency = 0,},
[ 2182 ]={  index = 2182, stagenum = 2, stateid = 6, name = [==[pumpkin plant]==], resourcebaseproficiency = 2, toolproficiency = 0,},
[ 2183 ]={  index = 2183, stagenum = 3, stateid = 6, name = [==[pumpkin plant]==], resourcebaseproficiency = 2, toolproficiency = 0,},
[ 2184 ]={  index = 2184, stagenum = 4, stateid = 6, name = [==[pumpkin plant]==], resourcebaseproficiency = 2, toolproficiency = 0,},
[ 2185 ]={  index = 2185, stagenum = 5, stateid = 6, name = [==[pumpkin plant]==], resourcebaseproficiency = 2, toolproficiency = 0,},
[ 2186 ]={  index = 2186, stagenum = 6, stateid = 6, name = [==[pumpkin plant]==], resourcebaseproficiency = 2, toolproficiency = 0,},
[ 8000 ]={  index = 8000, stagenum = 0, stateid = 0, name = [==[campfire]==], resourcebaseproficiency = 10, toolproficiency = 2,},
[ 4081 ]={  index = 4081, stagenum = 0, stateid = 0, name = [==[axe]==], resourcebaseproficiency = 10, toolproficiency = 2,},
[ 4084 ]={  index = 4084, stagenum = 0, stateid = 0, name = [==[pickaxe]==], resourcebaseproficiency = 10, toolproficiency = 0,},
[ 4124 ]={  index = 4124, stagenum = 0, stateid = 0, name = [==[spear]==], resourcebaseproficiency = 10, toolproficiency = 0,},
[ 4175 ]={  index = 4175, stagenum = 0, stateid = 0, name = [==[armorgrass]==], resourcebaseproficiency = 10, toolproficiency = 0,},
[ 4176 ]={  index = 4176, stagenum = 0, stateid = 0, name = [==[armorwood]==], resourcebaseproficiency = 10, toolproficiency = 0,},
[ 4094 ]={  index = 4094, stagenum = 0, stateid = 0, name = [==[torch]==], resourcebaseproficiency = 10, toolproficiency = 0,},
[ 8005 ]={  index = 8005, stagenum = 0, stateid = 0, name = [==[researchlab]==], resourcebaseproficiency = 10, toolproficiency = 0,},
[ 4086 ]={  index = 4086, stagenum = 0, stateid = 0, name = [==[shovel]==], resourcebaseproficiency = 10, toolproficiency = 2,},
[ 4089 ]={  index = 4089, stagenum = 0, stateid = 0, name = [==[hammer]==], resourcebaseproficiency = 10, toolproficiency = 2,},
[ 4092 ]={  index = 4092, stagenum = 0, stateid = 0, name = [==[bugnet]==], resourcebaseproficiency = 10, toolproficiency = 2,},
[ 4095 ]={  index = 4095, stagenum = 0, stateid = 0, name = [==[trap]==], resourcebaseproficiency = 10, toolproficiency = 0,},
[ 8024 ]={  index = 8024, stagenum = 0, stateid = 0, name = [==[tent]==], resourcebaseproficiency = 10, toolproficiency = 0,},
[ 8017 ]={  index = 8017, stagenum = 0, stateid = 0, name = [==[slow_farmplot]==], resourcebaseproficiency = 10, toolproficiency = 2,},
[ 8018 ]={  index = 8018, stagenum = 0, stateid = 0, name = [==[fast_farmplot]==], resourcebaseproficiency = 10, toolproficiency = 2,},
[ 4111 ]={  index = 4111, stagenum = 0, stateid = 0, name = [==[backpack]==], resourcebaseproficiency = 10, toolproficiency = 0,},
[ 4143 ]={  index = 4143, stagenum = 0, stateid = 0, name = [==[blowdart_pipe]==], resourcebaseproficiency = 10, toolproficiency = 0,},
[ 4145 ]={  index = 4145, stagenum = 0, stateid = 0, name = [==[4154.0]==], resourcebaseproficiency = 10, toolproficiency = 0,},
[ 8022 ]={  index = 8022, stagenum = 0, stateid = 0, name = [==[cookpot]==], resourcebaseproficiency = 10, toolproficiency = 2,},
[ 8012 ]={  index = 8012, stagenum = 0, stateid = 0, name = [==[treasurechest]==], resourcebaseproficiency = 10, toolproficiency = 0,},
[ 8135 ]={  index = 8135, stagenum = 0, stateid = 0, name = [==[corpse]==], resourcebaseproficiency = 10, toolproficiency = 0,},
[ 8044 ]={  index = 8044, stagenum = 0, stateid = 0, name = [==[pighouse]==], resourcebaseproficiency = 10, toolproficiency = 0,},
[ 8085 ]={  index = 8085, stagenum = 0, stateid = 0, name = [==[spiderden]==], resourcebaseproficiency = 10, toolproficiency = 0,},
[ 8076 ]={  index = 8076, stagenum = 0, stateid = 0, name = [==[beehive]==], resourcebaseproficiency = 10, toolproficiency = 0,},
[ 8138 ]={  index = 8138, stagenum = 0, stateid = 0, name = [==[beefaloherd]==], resourcebaseproficiency = 10, toolproficiency = 0,},
[ 8075 ]={  index = 8075, stagenum = 0, stateid = 0, name = [==[rabbit]==], resourcebaseproficiency = 10, toolproficiency = 0,},
[ 4234 ]={  index = 4234, stagenum = 0, stateid = 0, name = [==[cookedsmallmeat]==], resourcebaseproficiency = 10, toolproficiency = 0,},
[ 4224 ]={  index = 4224, stagenum = 0, stateid = 0, name = [==[berries_cooked]==], resourcebaseproficiency = 10, toolproficiency = 0,},
[ 4232 ]={  index = 4232, stagenum = 0, stateid = 0, name = [==[meat_dried]==], resourcebaseproficiency = 10, toolproficiency = 0,},
[ 4266 ]={  index = 4266, stagenum = 0, stateid = 0, name = [==[bonestew]==], resourcebaseproficiency = 10, toolproficiency = 0,},
[ 4045 ]={  index = 4045, stagenum = 0, stateid = 0, name = [==[poop]==], resourcebaseproficiency = 15, toolproficiency = 0,},
[ 4295 ]={  index = 4295, stagenum = 0, stateid = 0, name = [==[spoiled_food]==], resourcebaseproficiency = 10, toolproficiency = 0,},
[ 4294 ]={  index = 4294, stagenum = 0, stateid = 0, name = [==[wetgoop]==], resourcebaseproficiency = 5, toolproficiency = 0,},
}

return  live_level_lua_config